#!/bin/sh /etc/rc.common
#
# Copyright (C) 2021-2023 Morse Micro Pty Ltd. All rights reserved.
#

# It's important this happens before netifd sets up any
# morse interfaces, because the actual svg creation happens
# when there and /etc/dpp_key.pem must already exist.
START=11

boot() {
	if [ ! -e /etc/dpp_key.pem ]; then
		/morse/scripts/recover_dpp_key.sh /etc/dpp_key.pem
	fi
}