include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI HaLowLink 1 Guide
LUCI_DEPENDS:=+luci-base +luci-app-morseconfig

include $(TOPDIR)/feeds/luci/luci.mk


# call BuildPackage - OpenWrt buildroot signature
